#!/bin/sh
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train1000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes1000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train1500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes1500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train2000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes2000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train2500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes2500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train3000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes3000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train3500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes3500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train4000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes4000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train4500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes4500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train5000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes5000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train5500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes5500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train6000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes6000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train6500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes6500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train7000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes7000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train7500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes7500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train8000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes8000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train8500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes8500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train9000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes9000.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train9500.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes9500.txt
java -cp ./WEKA/weka.jar weka.classifiers.bayes.NaiveBayes -t ./output/3.2/train10000.arff -T ./output/test.arff -o > ./output/3.2/3.2output_bayes10000.txt